var orderHistory = [
  {
    orderPlaced: 'August 4, 2020',
    total: '$34.00',
    shipTo: 'JS Masher',
    orderNumber: 'ORDER # 114-3941689-8772232',
    orderDetails: 'Order Details',
    invoice: 'Invoice',
    deliveryDate: 'Delivered Aug 8, 2020',
    deliveryMethod: null,
    item: 'JavaScript for impatient programmers',
    author: 'Rauschmayer, Dr. Axel',
    returnWindow: 'Return window closed on Sep 7, 2020',
    subTotal: '$31.55',
    buyItAgain: 'Buy it again',
    viewItem: 'View your item',
    productSupport: null,
    writeReview: 'Write a product review'
  },
  {
    orderPlaced: 'July 19, 2020',
    total: '$44.53',
    shipTo: 'JS Masher',
    orderNumber: 'ORDER # 113-9984268-1280257',
    orderDetails: 'Order Details',
    invoice: 'Invoice',
    deliveryDate: 'Delivered Jul 20, 2020',
    deliveryMethod: 'Your package was delivered, It was handed directly to a resident.',
    item: 'The Timeless Way of Building',
    author: 'Alexander, Christopher',
    returnWindow: 'Return window closed on Aug 19, 2020',
    subTotal: '$41.33',
    buyItAgain: 'Buy it again',
    viewItem: 'View your item',
    productSupport: null,
    writeReview: 'Write a product review'
  },
  {
    orderPlaced: 'July 4, 2020',
    total: '$17.22',
    shipTo: 'JS Masher',
    orderNumber: 'ORDER # 114-2875557-9059409',
    orderDetails: 'Order Details',
    invoice: 'Invoice',
    deliveryDate: 'Delivered Jul 7, 2020',
    deliveryMethod: 'Your package was delivered. It was handed directly to a resident.',
    item: 'Gamecube Controller Adapter. Super Smash Bros Switch Gamecube Adapter for Wii U, PC. Support Turbo and Vibration features. No Driver and No Lag-Gamecube Adapter',
    author: null,
    returnWindow: 'Return window closed on Aug 5, 2020',
    subTotal: '$15.98',
    buyItAgain: 'Buy it again',
    viewItem: 'View your item',
    productSupport: null,
    writeReview: 'Write a product review'
  },
  {
    orderPlaced: 'July 3, 2020',
    total: '$138.93',
    shipTo: 'JS Masher',
    orderNumber: 'ORDER # 113-2883177-2648248',
    orderDetails: 'Order Details',
    invoice: 'Invoice',
    deliveryDate: 'Delivered Jul 5, 2020',
    deliveryMethod: null,
    item: ['GameCube Controller - Super Smash Bros. Edition (Nintendo Switch)', 'The Art of Sql'],
    author: [null, 'Faroult, Stephane'],
    returnWindow: 'Return window closed on Aug 4, 2020',
    subTotal: '$33.99',
    buyItAgain: 'Buy it again',
    viewItem: 'View your item',
    productSupport: 'Get product support',
    writeReview: 'Write a product review'
  }
];
